version: "3.9"
services:
  server:
    build: ./server
    depends_on:
      - db
    ports:
      - "80:5000"
    volumes:
      - ./server:/app
    environment:
      FLASK_ENV: development
    networks:
      - customNetwork

  web:
    build: ./reactapp
    ports:
      - "3000:3000"
    volumes:
      - ./reactapp:/user/src/app
    depends_on:
      - server
    networks:
      - customNetwork
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "90:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "deepmorindia2021"
      ACCEPT_EULA: Y
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    platform: linux/amd64
    networks:
      - customNetwork
networks:
  customNetwork:
